# Generated by Django 5.0.2 on 2024-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_table',
            name='img',
        ),
    ]
