# Generated by Django 5.0.2 on 2024-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_remove_student_table_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('classroom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='student_table',
            name='img',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
