# Generated by Django 5.0.2 on 2024-04-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_teacher_table_student_table_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('students', models.CharField(max_length=255)),
                ('teachers', models.CharField(max_length=255)),
                ('classrooms', models.CharField(max_length=255)),
            ],
        ),
    ]
