# Generated by Django 5.0.2 on 2024-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_rename_monthlylyfess_monthly_income_table_monthlyfess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_income_table',
            name='scholarshipawardedto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weekly_income_table',
            name='scholarshipawardedto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='yearly_income_table',
            name='scholarshipawardedto',
            field=models.CharField(max_length=255),
        ),
    ]
